// pages/list_page2.dart
import 'package:flutter/material.dart';
import 'reusable_list_page.dart';
import 'list_item.dart';

class ListPage2 extends StatelessWidget {
  const ListPage2({super.key});

  @override
  Widget build(BuildContext context) {
    final List<ListItem> items = [
      ListItem(
        number: 87,
        title: 'Ro Min RelSak Ang Che',
        imagePath: 'assets/2/87.jpg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 88,
        title: 'Aw Isu, Min Kai Ang che',
        imagePath: 'assets/2/88.jpg',
        soundPath: 'sounds/A.mp3',
        note: 'A',
      ),
      ListItem(
        number: 89,
        title: 'Lâwmna Tûr Hlir A Lo Ni Si',
        imagePath: 'assets/2/89.jpeg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 90,
        title: 'Min Hruai Zêl Dâwn',
        imagePath: 'assets/2/90.jpeg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 91,
        title: 'Tuarna Pawh Hlawkna',
        imagePath: 'assets/2/91.jpeg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 92,
        title: 'Siamtu Remruat',
        imagePath: 'assets/2/92.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 93,
        title: 'Ka Lawm E, LALPA',
        imagePath: 'assets/2/93.jpeg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 94,
        title: 'Khawvel A Boral Mêk',
        imagePath: 'assets/2/94.jpeg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 95,
        title: 'Tuarna Phêna Malsawmna',
        imagePath: 'assets/2/95.jpeg',
        soundPath: 'sounds/Gb.mp3',
        note: 'G♭',
      ),
      ListItem(
        number: 96,
        title: 'Phû Loh Hmangaihna',
        imagePath: 'assets/2/96.jpeg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 97,
        title: 'Damlai Tuipuiah Ka Thlarau A Vâkvai',
        imagePath: 'assets/2/97.jpeg',
        soundPath: 'sounds/Ab.mp3',
        note: 'A♭',
      ),
      ListItem(
        number: 98,
        title: 'Thlaler Tuivalawng',
        imagePath: 'assets/2/98.jpeg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 99,
        title: 'Harsatna Tinreng Hnuaia Leng',
        imagePath: 'assets/2/99.jpeg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 100,
        title: 'Hriat Chian Lehzual Che Ka Duh',
        imagePath: 'assets/2/100.jpeg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 101,
        title: 'Lâwmna Tlâng',
        imagePath: 'assets/2/101.jpeg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 102,
        title: 'Ka Lawm E, ISU',
        imagePath: 'assets/2/102.jpeg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 103,
        title: 'Lungawina Kim',
        imagePath: 'assets/2/103.jpeg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 104,
        title: 'Min Hmangaih Si A',
        imagePath: 'assets/2/104.jpeg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 105,
        title: 'Lalpa A Ṭha',
        imagePath: 'assets/2/105.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 106,
        title: 'Rimawi Ropui Ber',
        imagePath: 'assets/2/106.jpeg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 107,
        title: 'A Bo Tawh Ang',
        imagePath: 'assets/2/107.jpeg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 108,
        title: 'Chu Ngei Chu Ka Tân Van A Ni E',
        imagePath: 'assets/2/108.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 109,
        title: 'Ka LALPA Hnenah A Awm',
        imagePath: 'assets/2/109.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 110,
        title: 'Ropuina Ram Kalsanin',
        imagePath: 'assets/2/110.jpeg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 111,
        title: 'Lungawina Kim',
        imagePath: 'assets/2/111.jpeg',
        soundPath: 'sounds/Gb.mp3',
        note: 'G♭',
      ),
      ListItem(
        number: 112,
        title: 'Aw Hmangaihna',
        imagePath: 'assets/2/112.jpeg',
        soundPath: 'sounds/Ab.mp3',
        note: 'A♭',
      ),
      ListItem(
        number: 113,
        title: 'Krista Rilru',
        imagePath: 'assets/2/113.jpeg',
        soundPath: 'sounds/Ab.mp3',
        note: 'A♭',
      ),
      ListItem(
        number: 114,
        title: 'Min Hruai Ṭhin',
        imagePath: 'assets/2/114.jpeg',
        soundPath: 'sounds/Ab.mp3',
        note: 'A♭',
      ),
      ListItem(
        number: 115,
        title: 'Pathian Hmangaihna',
        imagePath: 'assets/2/115.jpeg',
        soundPath: 'sounds/Ab.mp3',
        note: 'A♭',
      ),
      ListItem(
        number: 116,
        title: 'Lal ISUA Hmangaihna',
        imagePath: 'assets/2/116.jpeg',
        soundPath: 'sounds/A.mp3',
        note: 'A',
      ),
      ListItem(
        number: 117,
        title: 'Thisen Thiltihtheihna',
        imagePath: 'assets/2/117.jpeg',
        soundPath: 'sounds/A.mp3',
        note: 'A',
      ),
      ListItem(
        number: 118,
        title: 'Zaiin Ka Hril Dawn',
        imagePath: 'assets/2/118.jpeg',
        soundPath: 'sounds/A.mp3',
        note: 'A',
      ),
      ListItem(
        number: 119,
        title: 'I Pianna Ramah Kir Leh Rawh',
        imagePath: 'assets/2/119.jpeg',
        soundPath: 'sounds/Bb.mp3',
        note: 'B♭',
      ),
      ListItem(
        number: 120,
        title: 'Suala Ka Bo Tawh Hnu',
        imagePath: 'assets/2/120.jpeg',
        soundPath: 'sounds/B.mp3',
        note: 'B',
      ),
      ListItem(
        number: 121,
        title: 'Sul Ni Leh Thla Kum Hunte Hian',
        imagePath: 'assets/2/121.jpeg',
        soundPath: 'sounds/B.mp3',
        note: 'B',
      ),
      ListItem(
        number: 122,
        title: 'Khaw Thianghlim Jerusalem',
        imagePath: 'assets/2/122.jpg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 123,
        title: 'Lei Leh Van Thil Zawngte Aiin',
        imagePath: 'assets/2/123.jpg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 124,
        title: 'A Pawi Lo Ve, Lalpa',
        imagePath: 'assets/2/124.jpeg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 125,
        title: 'Ka Duh Tu Dang Mah An Awm Lo',
        imagePath: 'assets/2/125.jpg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 126,
        title: 'Damlai Khawvelah Hian',
        imagePath: 'assets/2/126.jpeg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 127,
        title: 'Ka Duhber LALPA',
        imagePath: 'assets/2/127.jpeg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 128,
        title: 'Ram Thianghlim',
        imagePath: 'assets/2/128.jpeg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 129,
        title: 'Tlaitla Eng Mawi',
        imagePath: 'assets/2/129.jpeg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 130,
        title: 'Tuihal Rehna',
        imagePath: 'assets/2/130.jpg',
        soundPath: 'sounds/Db.mp3',
        note: 'D♭',
      ),
      ListItem(
        number: 131,
        title: 'Kan Zin Kawng Khawhar Takah',
        imagePath: 'assets/2/131.jpg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 132,
        title: 'Aw Van Thlarau Thianghlim Lo Leng Ang Che',
        imagePath: 'assets/2/132.jpeg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 133,
        title: 'Hawilo Par KRISTA',
        imagePath: 'assets/2/133.jpeg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 134,
        title: 'Lal ISUA Ṭhian Duhawm Ka Neih Hnu Hian',
        imagePath: 'assets/2/134.jpeg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 135,
        title: 'Lal ISUA Hnenah',
        imagePath: 'assets/2/135.jpeg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 136,
        title: 'Ka Lâwm Zêl Ang',
        imagePath: 'assets/2/136.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 137,
        title: 'Kan Fak Zêl Dâwn',
        imagePath: 'assets/2/137.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 138,
        title: 'Mi Sual Bo Hnu',
        imagePath: 'assets/2/138.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 139,
        title: 'Min Pe Tawh Zawk Ang',
        imagePath: 'assets/2/139.jpeg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 140,
        title: 'A Mak Mang E, Van Lal Ber Chuan',
        imagePath: 'assets/2/140.jpeg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 141,
        title: 'A Fingte Chu Van Êng Angin An Êng Ang',
        imagePath: 'assets/2/141.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 142,
        title: 'Amen, Lo Kal Ta Che LALPA ISU',
        imagePath: 'assets/2/142.jpg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 143,
        title: 'Ka Nung Reng Ang, KRISTAah Chuan',
        imagePath: 'assets/2/143.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 144,
        title: "Ka Tawrh Hi LALPA'n A Phal",
        imagePath: 'assets/2/144.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 145,
        title: "Kan Zin Kawngah",
        imagePath: 'assets/2/145.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 146,
        title: "Lal ISUA Kan Ṭhian Ṭha Berin",
        imagePath: 'assets/2/146.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 147,
        title: "Sawi Nawn Leh Rawh",
        imagePath: 'assets/2/147.jpg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
      ListItem(
        number: 148,
        title: "Min Tichaktu LALPA",
        imagePath: 'assets/2/148.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 149,
        title: "Tui Hna Thar",
        imagePath: 'assets/2/149.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 150,
        title: "Tui Nung Lui",
        imagePath: 'assets/2/150.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 151,
        title: "A Lo Kal Leh Dawn Lal ISUA",
        imagePath: 'assets/2/151.jpg',
        soundPath: 'sounds/Gb.mp3',
        note: 'G♭',
      ),
      ListItem(
        number: 152,
        title: "Inpeih Thuai Rawh",
        imagePath: 'assets/2/152.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 153,
        title: "Beram No Hnehna",
        imagePath: 'assets/2/153.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 154,
        title: "Buaina Khawvel",
        imagePath: 'assets/2/154.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 155,
        title: "Kawng Tluanin ISUA Ka Zui",
        imagePath: 'assets/2/155.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 156,
        title: "I Kal Zel Ang U",
        imagePath: 'assets/2/156.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 157,
        title: "Lal ISUA Chaknaa Innghatin",
        imagePath: 'assets/2/157.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 158,
        title: "Kan ISUA Ang Ṭhian Dang Rêng",
        imagePath: 'assets/2/158.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 159,
        title: "Thim A Awm Tawh Lovang, A Lo Kalin",
        imagePath: 'assets/2/159.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 160,
        title: "ISU, Ka Hmangaih Che, Ka Ta I Ni E",
        imagePath: 'assets/2/160.jpg',
        soundPath: 'sounds/F.mp3',
        note: 'F',
      ),
      ListItem(
        number: 161,
        title: "Rinna Thla Zâr Ila",
        imagePath: 'assets/2/161.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 162,
        title: "He Dam Chhung Buaithlak",
        imagePath: 'assets/2/162.jpg',
        soundPath: 'sounds/G.mp3',
        note: 'G',
      ),
      ListItem(
        number: 163,
        title: "Ka Chenna Ram Thlaler A Ni",
        imagePath: 'assets/2/163.jpg',
        soundPath: 'sounds/Ab.mp3',
        note: 'A♭',
      ),
      ListItem(
        number: 164,
        title: "Hlau Suh, Ka Awmpui Che",
        imagePath: 'assets/2/164.jpg',
        soundPath: 'sounds/C.mp3',
        note: 'C',
      ),
      ListItem(
        number: 165,
        title: "Ka Damlai Nun Kawng Hi",
        imagePath: 'assets/2/165.jpg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 166,
        title: "Pathian Hmangaihna Ropuizia",
        imagePath: 'assets/2/166.jpg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 167,
        title: "Van Lawmna Kim",
        imagePath: 'assets/2/167.jpg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 168,
        title: "A Hmangaihna A Lo Ni",
        imagePath: 'assets/2/168.jpg',
        soundPath: 'sounds/D_2.mp3',
        note: 'D',
      ),
      ListItem(
        number: 169,
        title: "I Ṭap Thawmah I LALPA A Tho",
        imagePath: 'assets/2/169.jpg',
        soundPath: 'sounds/Eb.mp3',
        note: 'E♭',
      ),
      ListItem(
        number: 170,
        title: "Ringtu Ṭawngṭaina",
        imagePath: 'assets/2/170.jpg',
        soundPath: 'sounds/E.mp3',
        note: 'E',
      ),
    ];

    return ReusableListPage(title: 'Page 2', items: items);
  }
}
